#!/usr/bin/env python3
"""Shared SQL builders + paths for the dictionary site sync.

This module is a LIBRARY for scripts/dictionary/sync_from_site.py — the
seo-app-v2 raw-fetch entrypoint was removed (2026-08-23) when the sync pivoted
to site-as-storage (see docs/dictionary-sync.md); nothing here talks to
seo-app-v2 anymore.

- A migration is only written when the term set changed (hash compare against
  data/dictionary/.sync_state.json), so scheduled runs are no-ops until the
  dictionary actually changes.
- build_migration refuses duplicate term keys: ON CONFLICT DO UPDATE aborts
  the whole statement with SQLSTATE 21000 if one INSERT touches a row twice,
  so dupes must be resolved before SQL generation (sync_from_site.dedupe_records).
"""
from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
STATE = REPO / "data" / "dictionary" / ".sync_state.json"
LOCAL_COPY = REPO / "data" / "dictionary" / "glossary_normalized.json"
MIGRATIONS = REPO / "supabase" / "migrations"


def sql_quote(value) -> str:
    """Render a value as a SQL literal ($glossary$ quoting for text)."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if "$glossary$" in text:
        raise ValueError("dollar-quote delimiter inside value")
    return f"$glossary${text}$glossary$"


def arr(values) -> str:
    if not values:
        return "ARRAY[]::text[]"
    inner = ", ".join(sql_quote(v) for v in values)
    return f"ARRAY[{inner}]::text[]"


def build_migration(records: list[dict]) -> str:
    terms = [r["term"] for r in records]
    if len(set(t.lower() for t in terms)) != len(terms):
        raise ValueError(
            "duplicate term keys in records — dedupe before build_migration "
            "(ON CONFLICT DO UPDATE would fail with SQLSTATE 21000)"
        )
    rows = []
    for rec in records:
        cat = sql_quote(rec.get("category"))
        rows.append(
            f"  ({sql_quote(rec['term'])}, {sql_quote(rec.get('definition'))}, "
            f"{cat}, {arr(rec.get('categories'))}, {arr(rec.get('related_terms'))}, "
            f"{sql_quote(rec.get('slug'))}, {sql_quote(rec.get('source_url'))})"
        )
    joined = ",\n".join(rows)
    return f"""-- Dictionary sync from coffee-dictionary.com — {len(records)} terms, generated by
-- coffee-apps scripts/dictionary/sync_from_site.py. Definition = the lead
-- (first paragraph) of each article; full content lives on coffee-dictionary.com,
-- linked via source_url. Idempotent: unique term index + upsert.

create unique index if not exists glossary_terms_term_key
  on public.glossary_terms (term);

insert into public.glossary_terms (term, definition, category, categories, related_terms, slug, source_url)
values
{joined}
on conflict (term) do update set
  definition = excluded.definition,
  category = excluded.category,
  categories = excluded.categories,
  related_terms = excluded.related_terms,
  slug = excluded.slug,
  source_url = excluded.source_url;
"""
