#!/usr/bin/env python3
"""Fetch the dictionary export from seo-app-v2 (GitHub raw) and generate a
Supabase upsert migration for glossary_terms.

Sync contract (see docs/dictionary-sync.md):
- Source of truth: seo-app-v2 · dictionary-import/data/glossary_normalized.json
- This script only READS that file and generates an idempotent migration;
  nothing here edits dictionary content.
- A migration is only written when the term set changed (hash compare against
  data/dictionary/.sync_state.json), so scheduled runs are no-ops until the
  dictionary actually changes.

Usage:
  python3 scripts/dictionary/fetch_and_generate.py            # local dev
  # in CI, SEO_APP_READ_TOKEN + source env vars are set by the workflow

Exit codes: 0 = ok (change or no-change), 1 = fetch/parse failure.
Prints "CHANGED <path>" or "UNCHANGED" as the last line for CI.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
import sys
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RAW_URL = os.environ.get(
    "DICTIONARY_RAW_URL",
    "https://raw.githubusercontent.com/dorianbodnariuc/seo-app-v2/main/"
    "dictionary-import/data/glossary_normalized.json",
)
STATE = REPO / "data" / "dictionary" / ".sync_state.json"
LOCAL_COPY = REPO / "data" / "dictionary" / "glossary_normalized.json"
MIGRATIONS = REPO / "supabase" / "migrations"


def fetch() -> list[dict]:
    req = urllib.request.Request(RAW_URL)
    token = os.environ.get("SEO_APP_READ_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=60) as r:
        data = json.loads(r.read().decode("utf-8"))
    if not isinstance(data, list) or not data or "term" not in data[0]:
        raise ValueError(f"unexpected export shape: {type(data)}")
    return data


def sql_quote(value) -> str:
    """Render a value as a SQL literal ($glossary$ quoting for text)."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    text = str(value)
    if "$glossary$" in text:
        raise ValueError("dollar-quote delimiter inside value")
    return f"$glossary${text}$glossary$"


def arr(values) -> str:
    if not values:
        return "ARRAY[]::text[]"
    inner = ", ".join(sql_quote(v) for v in values)
    return f"ARRAY[{inner}]::text[]"


def build_migration(records: list[dict]) -> str:
    rows = []
    for rec in records:
        cat = sql_quote(rec.get("category"))
        rows.append(
            f"  ({sql_quote(rec['term'])}, {sql_quote(rec.get('definition'))}, "
            f"{cat}, {arr(rec.get('categories'))}, {arr(rec.get('related_terms'))}, "
            f"{sql_quote(rec.get('slug'))}, {sql_quote(rec.get('source_url'))})"
        )
    joined = ",\n".join(rows)
    return f"""-- Dictionary sync from seo-app-v2 — {len(records)} terms, generated by
-- coffee-apps scripts/dictionary/fetch_and_generate.py. Definition = the lead
-- (first paragraph) of each article; full content lives on coffee-dictionary.com,
-- linked via source_url. Idempotent: unique term index + upsert.

create unique index if not exists glossary_terms_term_key
  on public.glossary_terms (term);

insert into public.glossary_terms (term, definition, category, categories, related_terms, slug, source_url)
values
{joined}
on conflict (term) do update set
  definition = excluded.definition,
  category = excluded.category,
  categories = excluded.categories,
  related_terms = excluded.related_terms,
  slug = excluded.slug,
  source_url = excluded.source_url;
"""


def main() -> int:
    records = fetch()
    print(f"fetched {len(records)} terms")
    payload = json.dumps(records, sort_keys=True, ensure_ascii=False)
    new_hash = hashlib.sha256(payload.encode()).hexdigest()

    LOCAL_COPY.parent.mkdir(parents=True, exist_ok=True)
    LOCAL_COPY.write_text(json.dumps(records, indent=2, ensure_ascii=False) + "\n")

    state = json.loads(STATE.read_text()) if STATE.exists() else {}
    if state.get("hash") == new_hash:
        print("UNCHANGED")
        return 0

    stamp = dt.datetime.now(dt.timezone.utc).strftime("%Y%m%d%H%M%S")
    MIGRATIONS.mkdir(parents=True, exist_ok=True)
    # The sync migration must sort AFTER every existing migration file, or
    # `supabase db push` rejects it (files inserted before the remote's last
    # applied migration). Existing stamps can be future-dated relative to now
    # (e.g. manual migrations staged ahead), so bump past the max. Only the
    # numeric ordering matters — int(max)+1 always sorts after max.
    import re as _re
    stems = [m.group(1) for p in MIGRATIONS.glob("*.sql")
             if (m := _re.match(r"(\d+)", p.stem))]
    if stems and stamp <= max(stems):  # lexicographic = supabase's file order
        stamp = str(int(max(stems)) + 1)
    path = MIGRATIONS / f"{stamp}_glossary_sync.sql"
    path.write_text(build_migration(records))
    STATE.write_text(json.dumps({
        "hash": new_hash,
        "terms": len(records),
        "migration": path.name,
        "synced_at": dt.datetime.now(dt.timezone.utc).isoformat(),
    }, indent=1) + "\n")
    print(f"CHANGED {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
