-- T24 seed — curated origin taxonomy + famous roasters (D-032).
-- Origins are a near-closed taxonomy (country + region); roasters are globally
-- recognizable specialty names to make typeahead feel alive on day one. No bean
-- SKU catalog. `on conflict do nothing` makes this idempotent (dedup key =
-- normalized name).

-- Countries (region = null) + well-known regions (region = the region name).
insert into public.origins (name, country, region) values
  -- Africa
  ('Ethiopia', 'Ethiopia', null),
  ('Yirgacheffe', 'Ethiopia', 'Yirgacheffe'),
  ('Sidamo', 'Ethiopia', 'Sidamo'),
  ('Guji', 'Ethiopia', 'Guji'),
  ('Harrar', 'Ethiopia', 'Harrar'),
  ('Limu', 'Ethiopia', 'Limu'),
  ('Jimma', 'Ethiopia', 'Jimma'),
  ('Kaffa', 'Ethiopia', 'Kaffa'),
  ('Kenya', 'Kenya', null),
  ('Nyeri', 'Kenya', 'Nyeri'),
  ('Kirinyaga', 'Kenya', 'Kirinyaga'),
  ('Murang''a', 'Kenya', 'Murang''a'),
  ('Embu', 'Kenya', 'Embu'),
  ('Kiambu', 'Kenya', 'Kiambu'),
  ('Machakos', 'Kenya', 'Machakos'),
  ('Rwanda', 'Rwanda', null),
  ('Nyamagabe', 'Rwanda', 'Nyamagabe'),
  ('Huye', 'Rwanda', 'Huye'),
  ('Gakenke', 'Rwanda', 'Gakenke'),
  ('Burundi', 'Burundi', null),
  ('Kayanza', 'Burundi', 'Kayanza'),
  ('Ngozi', 'Burundi', 'Ngozi'),
  ('Muyinga', 'Burundi', 'Muyinga'),
  ('Tanzania', 'Tanzania', null),
  ('Kilimanjaro', 'Tanzania', 'Kilimanjaro'),
  ('Mbeya', 'Tanzania', 'Mbeya'),
  ('Arusha', 'Tanzania', 'Arusha'),
  ('Uganda', 'Uganda', null),
  ('Mount Elgon', 'Uganda', 'Mount Elgon'),
  ('Rwenzori', 'Uganda', 'Rwenzori'),
  ('Sipi Falls', 'Uganda', 'Sipi Falls'),
  ('DR Congo', 'DR Congo', null),
  ('Kivu', 'DR Congo', 'Kivu'),
  ('Malawi', 'Malawi', null),
  ('Mzuzu', 'Malawi', 'Mzuzu'),
  -- Central & South America
  ('Colombia', 'Colombia', null),
  ('Huila', 'Colombia', 'Huila'),
  ('Nariño', 'Colombia', 'Nariño'),
  ('Cauca', 'Colombia', 'Cauca'),
  ('Antioquia', 'Colombia', 'Antioquia'),
  ('Tolima', 'Colombia', 'Tolima'),
  ('Santander', 'Colombia', 'Santander'),
  ('Quindío', 'Colombia', 'Quindío'),
  ('Brazil', 'Brazil', null),
  ('Minas Gerais', 'Brazil', 'Minas Gerais'),
  ('Cerrado', 'Brazil', 'Cerrado'),
  ('Sul de Minas', 'Brazil', 'Sul de Minas'),
  ('Mogiana', 'Brazil', 'Mogiana'),
  ('Espírito Santo', 'Brazil', 'Espírito Santo'),
  ('Bahia', 'Brazil', 'Bahia'),
  ('Guatemala', 'Guatemala', null),
  ('Antigua', 'Guatemala', 'Antigua'),
  ('Huehuetenango', 'Guatemala', 'Huehuetenango'),
  ('Acatenango', 'Guatemala', 'Acatenango'),
  ('Atitlán', 'Guatemala', 'Atitlán'),
  ('Cobán', 'Guatemala', 'Cobán'),
  ('Costa Rica', 'Costa Rica', null),
  ('Tarrazú', 'Costa Rica', 'Tarrazú'),
  ('Naranjo', 'Costa Rica', 'Naranjo'),
  ('West Valley', 'Costa Rica', 'West Valley'),
  ('Tres Ríos', 'Costa Rica', 'Tres Ríos'),
  ('Brunca', 'Costa Rica', 'Brunca'),
  ('Honduras', 'Honduras', null),
  ('Copán', 'Honduras', 'Copán'),
  ('Marcala', 'Honduras', 'Marcala'),
  ('Montecillos', 'Honduras', 'Montecillos'),
  ('Nicaragua', 'Nicaragua', null),
  ('Jinotega', 'Nicaragua', 'Jinotega'),
  ('Matagalpa', 'Nicaragua', 'Matagalpa'),
  ('Nueva Segovia', 'Nicaragua', 'Nueva Segovia'),
  ('El Salvador', 'El Salvador', null),
  ('Santa Ana', 'El Salvador', 'Santa Ana'),
  ('Apaneca', 'El Salvador', 'Apaneca'),
  ('Panama', 'Panama', null),
  ('Boquete', 'Panama', 'Boquete'),
  ('Volcán', 'Panama', 'Volcán'),
  ('Mexico', 'Mexico', null),
  ('Chiapas', 'Mexico', 'Chiapas'),
  ('Oaxaca', 'Mexico', 'Oaxaca'),
  ('Veracruz', 'Mexico', 'Veracruz'),
  ('Peru', 'Peru', null),
  ('Cajamarca', 'Peru', 'Cajamarca'),
  ('Cusco', 'Peru', 'Cusco'),
  ('Junín', 'Peru', 'Junín'),
  ('San Martín', 'Peru', 'San Martín'),
  ('Bolivia', 'Bolivia', null),
  ('Yungas', 'Bolivia', 'Yungas'),
  ('Caranavi', 'Bolivia', 'Caranavi'),
  ('Ecuador', 'Ecuador', null),
  ('Loja', 'Ecuador', 'Loja'),
  ('Pichincha', 'Ecuador', 'Pichincha'),
  -- Caribbean
  ('Jamaica', 'Jamaica', null),
  ('Blue Mountain', 'Jamaica', 'Blue Mountain'),
  ('Dominican Republic', 'Dominican Republic', null),
  ('Barahona', 'Dominican Republic', 'Barahona'),
  ('Cuba', 'Cuba', null),
  ('Sierra Maestra', 'Cuba', 'Sierra Maestra'),
  ('Puerto Rico', 'Puerto Rico', null),
  ('Yauco', 'Puerto Rico', 'Yauco'),
  -- Asia-Pacific
  ('Indonesia', 'Indonesia', null),
  ('Sumatra', 'Indonesia', 'Sumatra'),
  ('Gayo', 'Indonesia', 'Gayo'),
  ('Mandheling', 'Indonesia', 'Mandheling'),
  ('Java', 'Indonesia', 'Java'),
  ('Sulawesi', 'Indonesia', 'Sulawesi'),
  ('Toraja', 'Indonesia', 'Toraja'),
  ('Bali', 'Indonesia', 'Bali'),
  ('Flores', 'Indonesia', 'Flores'),
  ('Vietnam', 'Vietnam', null),
  ('Dalat', 'Vietnam', 'Dalat'),
  ('India', 'India', null),
  ('Chikmagalur', 'India', 'Chikmagalur'),
  ('Coorg', 'India', 'Coorg'),
  ('Wayanad', 'India', 'Wayanad'),
  ('Yemen', 'Yemen', null),
  ('Mocha', 'Yemen', 'Mocha'),
  ('Haraaz', 'Yemen', 'Haraaz'),
  ('China', 'China', null),
  ('Yunnan', 'China', 'Yunnan'),
  ('Thailand', 'Thailand', null),
  ('Chiang Mai', 'Thailand', 'Chiang Mai'),
  ('Chiang Rai', 'Thailand', 'Chiang Rai'),
  ('Myanmar', 'Myanmar', null),
  ('Shan State', 'Myanmar', 'Shan State'),
  ('Laos', 'Laos', null),
  ('Bolaven Plateau', 'Laos', 'Bolaven Plateau'),
  ('Papua New Guinea', 'Papua New Guinea', null),
  ('Eastern Highlands', 'Papua New Guinea', 'Eastern Highlands'),
  ('Western Highlands', 'Papua New Guinea', 'Western Highlands'),
  ('Hawaii', 'United States', 'Hawaii'),
  ('Kona', 'United States', 'Kona'),
  ('Ka''u', 'United States', 'Ka''u'),
  ('Maui', 'United States', 'Maui'),
  ('Australia', 'Australia', null),
  ('Skybury', 'Australia', 'Skybury')
on conflict do nothing;

-- Famous specialty roasters (name + country + city). `subscribed` stays false;
-- paid fields are filled only for claimed profiles later (D-030/D-031).
insert into public.roasters (name, country, city) values
  ('Blue Bottle Coffee', 'United States', 'Oakland, CA'),
  ('Intelligentsia Coffee', 'United States', 'Chicago, IL'),
  ('Stumptown Coffee Roasters', 'United States', 'Portland, OR'),
  ('Counter Culture Coffee', 'United States', 'Durham, NC'),
  ('Onyx Coffee Lab', 'United States', 'Rogers, AR'),
  ('Verve Coffee Roasters', 'United States', 'Santa Cruz, CA'),
  ('Heart Coffee Roasters', 'United States', 'Portland, OR'),
  ('Ritual Coffee Roasters', 'United States', 'San Francisco, CA'),
  ('Sightglass Coffee', 'United States', 'San Francisco, CA'),
  ('George Howell Coffee', 'United States', 'Acton, MA'),
  ('Sey Coffee', 'United States', 'Brooklyn, NY'),
  ('Passenger Coffee', 'United States', 'Lancaster, PA'),
  ('Madcap Coffee', 'United States', 'Grand Rapids, MI'),
  ('Ruby Coffee Roasters', 'United States', 'Nelsonville, WI'),
  ('Tandem Coffee Roasters', 'United States', 'Portland, ME'),
  ('Equator Coffees', 'United States', 'San Rafael, CA'),
  ('Coava Coffee Roasters', 'United States', 'Portland, OR'),
  ('Sweet Bloom Coffee Roasters', 'United States', 'Lakewood, CO'),
  ('La Colombe Coffee Roasters', 'United States', 'Philadelphia, PA'),
  ('Camber Coffee', 'United States', 'Bellingham, WA'),
  ('Cat & Cloud Coffee', 'United States', 'Santa Cruz, CA'),
  ('Vibrant Coffee Roasters', 'United States', 'Philadelphia, PA'),
  ('Little Wolf Coffee', 'United States', 'Ipswich, MA'),
  ('Square Mile Coffee Roasters', 'United Kingdom', 'London'),
  ('Workshop Coffee', 'United Kingdom', 'London'),
  ('Hasbean', 'United Kingdom', 'Stafford'),
  ('Origin Coffee Roasters', 'United Kingdom', 'Helston'),
  ('Caravan Coffee Roasters', 'United Kingdom', 'London'),
  ('Colonna Coffee', 'United Kingdom', 'Bath'),
  ('Tim Wendelboe', 'Norway', 'Oslo'),
  ('Coffee Collective', 'Denmark', 'Copenhagen'),
  ('Koppi', 'Sweden', 'Helsingborg'),
  ('Drop Coffee', 'Sweden', 'Stockholm'),
  ('La Cabra', 'Denmark', 'Aarhus'),
  ('Fuglen Coffee Roasters', 'Norway', 'Oslo'),
  ('The Barn', 'Germany', 'Berlin'),
  ('Five Elephant', 'Germany', 'Berlin'),
  ('Bonanza Coffee Roasters', 'Germany', 'Berlin'),
  ('Man versus Machine', 'Germany', 'Munich'),
  ('Gardelli Specialty Coffees', 'Italy', 'Forlì'),
  ('Ditta Artigianale', 'Italy', 'Florence'),
  ('Bocca Coffee', 'Netherlands', 'Amsterdam'),
  ('Friedhats Coffee Roasters', 'Netherlands', 'Amsterdam'),
  ('49th Parallel Coffee Roasters', 'Canada', 'Vancouver, BC'),
  ('Phil & Sebastian Coffee Roasters', 'Canada', 'Calgary, AB'),
  ('Monogram Coffee', 'Canada', 'Calgary, AB'),
  ('Pilot Coffee Roasters', 'Canada', 'Toronto, ON'),
  ('Matchstick Coffee Roasters', 'Canada', 'Vancouver, BC'),
  ('Single O', 'Australia', 'Sydney'),
  ('Campos Coffee', 'Australia', 'Sydney'),
  ('Market Lane Coffee', 'Australia', 'Melbourne'),
  ('Seven Seeds', 'Australia', 'Melbourne'),
  ('Proud Mary Coffee', 'Australia', 'Melbourne'),
  ('St. Ali', 'Australia', 'Melbourne'),
  ('Coffee Supreme', 'New Zealand', 'Wellington'),
  ('Kurasu', 'Japan', 'Kyoto'),
  ('Glitch Coffee & Roasters', 'Japan', 'Tokyo'),
  ('Onibus Coffee', 'Japan', 'Tokyo'),
  ('% Arabica', 'Japan', 'Kyoto')
on conflict do nothing;
