-- T11b: Add slug column + unique index to support alias-aware dictionary search.
ALTER TABLE glossary_terms ADD COLUMN IF NOT EXISTS slug text;
CREATE UNIQUE INDEX IF NOT EXISTS idx_glossary_terms_slug ON glossary_terms(slug);
UPDATE glossary_terms SET slug = 'aa-coffee-grading' WHERE term = 'AA Coffee Grading';
UPDATE glossary_terms SET slug = 'acrid-coffee-taste' WHERE term = 'Acrid Coffee Taste';
UPDATE glossary_terms SET slug = 'aeropress' WHERE term = 'AeroPress';
UPDATE glossary_terms SET slug = 'aerobie' WHERE term = 'Aerobie';
UPDATE glossary_terms SET slug = 'affogato' WHERE term = 'Affogato';
UPDATE glossary_terms SET slug = 'after-dinner-roast' WHERE term = 'After Dinner Roast';
UPDATE glossary_terms SET slug = 'aftertaste-in-coffee' WHERE term = 'Aftertaste in Coffee';
UPDATE glossary_terms SET slug = 'aftertastes' WHERE term = 'Aftertastes';
UPDATE glossary_terms SET slug = 'aged-coffee' WHERE term = 'Aged Coffee';
UPDATE glossary_terms SET slug = 'ageing' WHERE term = 'Ageing';
UPDATE glossary_terms SET slug = 'air-roaster' WHERE term = 'Air Roaster';
UPDATE glossary_terms SET slug = 'alan-adler' WHERE term = 'Alan Adler';
UPDATE glossary_terms SET slug = 'alkaline-taste-in-coffee' WHERE term = 'Alkaline Taste in Coffee';
UPDATE glossary_terms SET slug = 'altura-coffee' WHERE term = 'Altura Coffee';
UPDATE glossary_terms SET slug = 'alzheimers-disease' WHERE term = 'Alzheimer’s disease';
UPDATE glossary_terms SET slug = 'american-roast' WHERE term = 'American Roast';
UPDATE glossary_terms SET slug = 'antestia-bug-damage-on-coffee-beans' WHERE term = 'Antestia Bug Damage';
UPDATE glossary_terms SET slug = 'arabian-mocha-coffee' WHERE term = 'Arabian Mocha Coffee';
UPDATE glossary_terms SET slug = 'arabic-coffee' WHERE term = 'Arabic coffee';
UPDATE glossary_terms SET slug = 'artisan-coffee' WHERE term = 'Artisan Coffee';
UPDATE glossary_terms SET slug = 'arusha-coffee' WHERE term = 'Arusha Coffee';
UPDATE glossary_terms SET slug = 'ashy-coffee' WHERE term = 'Ashy Coffee';
UPDATE glossary_terms SET slug = 'asian-palm-civet' WHERE term = 'Asian palm civet';
UPDATE glossary_terms SET slug = 'aspiration-in-coffee-tasting' WHERE term = 'Aspiration in Coffee Tasting';
UPDATE glossary_terms SET slug = 'astringency-in-coffee' WHERE term = 'Astringency in Coffee';
UPDATE glossary_terms SET slug = 'australia' WHERE term = 'Australia';
UPDATE glossary_terms SET slug = 'baggy-coffee' WHERE term = 'Baggy Coffee';
UPDATE glossary_terms SET slug = 'baked-coffee' WHERE term = 'Baked Coffee';
UPDATE glossary_terms SET slug = 'balance-in-coffee' WHERE term = 'Balance in Coffee';
UPDATE glossary_terms SET slug = 'bar-unit' WHERE term = 'Bar (unit)';
UPDATE glossary_terms SET slug = 'barista' WHERE term = 'Barista';
UPDATE glossary_terms SET slug = 'beaker-glassware' WHERE term = 'Beaker (glassware)';
UPDATE glossary_terms SET slug = 'bean-hopper' WHERE term = 'Bean Hopper';
UPDATE glossary_terms SET slug = 'beko' WHERE term = 'Beko';
UPDATE glossary_terms SET slug = 'bialetti' WHERE term = 'Bialetti';
UPDATE glossary_terms SET slug = 'bialetti-moka-express' WHERE term = 'Bialetti Moka Express';
UPDATE glossary_terms SET slug = 'bica' WHERE term = 'Bica';
UPDATE glossary_terms SET slug = 'bicerin' WHERE term = 'Bicerin';
UPDATE glossary_terms SET slug = 'bisphenol-a' WHERE term = 'Bisphenol A';
UPDATE glossary_terms SET slug = 'bitterness-in-coffee' WHERE term = 'Bitterness in Coffee';
UPDATE glossary_terms SET slug = 'black-decker' WHERE term = 'Black & Decker';
UPDATE glossary_terms SET slug = 'black-eye' WHERE term = 'Black eye';
UPDATE glossary_terms SET slug = 'bodum' WHERE term = 'Bodum';
UPDATE glossary_terms SET slug = 'boiler' WHERE term = 'Boiler';
UPDATE glossary_terms SET slug = 'bonavita' WHERE term = 'Bonavita';
UPDATE glossary_terms SET slug = 'borosilicate-glass' WHERE term = 'Borosilicate glass';
UPDATE glossary_terms SET slug = 'brain-damage' WHERE term = 'Brain damage';
UPDATE glossary_terms SET slug = 'bready-coffee-a-sign-of-underdevelopment' WHERE term = 'Bready Coffee';
UPDATE glossary_terms SET slug = 'breve' WHERE term = 'Breve';
UPDATE glossary_terms SET slug = 'breville' WHERE term = 'Breville';
UPDATE glossary_terms SET slug = 'brightness-in-coffee-a-tangy-flavor-profile' WHERE term = 'Brightness in Coffee';
UPDATE glossary_terms SET slug = 'brikka-pot' WHERE term = 'Brikka pot';
UPDATE glossary_terms SET slug = 'briny-coffee-taste-and-flavor-descriptors' WHERE term = 'Briny';
UPDATE glossary_terms SET slug = 'bucharest' WHERE term = 'Bucharest';
UPDATE glossary_terms SET slug = 'bunn-o-matic-corporation' WHERE term = 'Bunn-o-Matic Corporation';
UPDATE glossary_terms SET slug = 'burr-grinder' WHERE term = 'Burr Grinder';
UPDATE glossary_terms SET slug = 'cafestol' WHERE term = 'Cafestol';
UPDATE glossary_terms SET slug = 'caffe-americano' WHERE term = 'Caffe Americano';
UPDATE glossary_terms SET slug = 'caffeine' WHERE term = 'Caffeine';
UPDATE glossary_terms SET slug = 'caffeine-extraction' WHERE term = 'Caffeine Extraction';
UPDATE glossary_terms SET slug = 'caffe-latte' WHERE term = 'Caffè Latte';
UPDATE glossary_terms SET slug = 'caffe-mocha' WHERE term = 'Caffè Mocha';
UPDATE glossary_terms SET slug = 'caffe-crema' WHERE term = 'Caffè crema';
UPDATE glossary_terms SET slug = 'cafe-bombon' WHERE term = 'Café Bombón';
UPDATE glossary_terms SET slug = 'cafe-romano' WHERE term = 'Café Romano';
UPDATE glossary_terms SET slug = 'cafe-au-lait' WHERE term = 'Café au lait';
UPDATE glossary_terms SET slug = 'cafe-con-leche' WHERE term = 'Café con Leche';
UPDATE glossary_terms SET slug = 'camp-coffee' WHERE term = 'Camp Coffee';
UPDATE glossary_terms SET slug = 'cancer' WHERE term = 'Cancer';
UPDATE glossary_terms SET slug = 'cappuccino' WHERE term = 'Cappuccino';
UPDATE glossary_terms SET slug = 'cappuccino-machine' WHERE term = 'Cappuccino Machine';
UPDATE glossary_terms SET slug = 'capresso' WHERE term = 'Capresso';
UPDATE glossary_terms SET slug = 'caramelization' WHERE term = 'Caramelization';
UPDATE glossary_terms SET slug = 'caramelly-a-sweet-note-in-coffee-tasting' WHERE term = 'Caramelly';
UPDATE glossary_terms SET slug = 'carbony-coffee-flavor-profiles' WHERE term = 'Carbony';
UPDATE glossary_terms SET slug = 'caro' WHERE term = 'Caro Beverage';
UPDATE glossary_terms SET slug = 'ceramic' WHERE term = 'Ceramic';
UPDATE glossary_terms SET slug = 'cezve' WHERE term = 'Cezve';
UPDATE glossary_terms SET slug = 'chameleon-cold-brew' WHERE term = 'Chameleon Cold-Brew';
UPDATE glossary_terms SET slug = 'channeling' WHERE term = 'Channeling';
UPDATE glossary_terms SET slug = 'chemex-coffeemaker' WHERE term = 'Chemex Coffeemaker';
UPDATE glossary_terms SET slug = 'chicory' WHERE term = 'Chicory';
UPDATE glossary_terms SET slug = 'chocolate-coffee-notes' WHERE term = 'Chocolate Coffee Notes';
UPDATE glossary_terms SET slug = 'cholesterol' WHERE term = 'Cholesterol';
UPDATE glossary_terms SET slug = 'citrus-in-coffee-a-flavor-profile' WHERE term = 'Citrus in Coffee';
UPDATE glossary_terms SET slug = 'clean-coffee-dictionary-term' WHERE term = 'Clean Coffee';
UPDATE glossary_terms SET slug = 'cocktail-shaker' WHERE term = 'Cocktail Shaker';
UPDATE glossary_terms SET slug = 'coffea' WHERE term = 'Coffea';
UPDATE glossary_terms SET slug = 'coffea-arabica' WHERE term = 'Coffea Arabica';
UPDATE glossary_terms SET slug = 'coffea-charrieriana' WHERE term = 'Coffea charrieriana';
UPDATE glossary_terms SET slug = 'coffea-liberica' WHERE term = 'Coffea liberica';
UPDATE glossary_terms SET slug = 'coffee-acidity' WHERE term = 'Coffee Acidity';
UPDATE glossary_terms SET slug = 'coffee-aroma' WHERE term = 'Coffee Aroma';
UPDATE glossary_terms SET slug = 'coffee-bloom' WHERE term = 'Coffee Bloom';
UPDATE glossary_terms SET slug = 'coffee-body-the-texture-and-mouthfeel-of-coffee' WHERE term = 'Coffee Body';
UPDATE glossary_terms SET slug = 'coffee-bouquet-the-aroma-of-freshly-ground-coffee' WHERE term = 'Coffee Bouquet';
UPDATE glossary_terms SET slug = 'coffee-brewing' WHERE term = 'Coffee Brewing';
UPDATE glossary_terms SET slug = 'coffee-brewing-methods' WHERE term = 'Coffee Brewing Methods';
UPDATE glossary_terms SET slug = 'water-temperature' WHERE term = 'Coffee Brewing Temperature';
UPDATE glossary_terms SET slug = 'coffee-cabinet' WHERE term = 'Coffee Cabinet';
UPDATE glossary_terms SET slug = 'coffee-concentrate' WHERE term = 'Coffee Concentrate';
UPDATE glossary_terms SET slug = 'coffee-puck' WHERE term = 'Coffee Puck';
UPDATE glossary_terms SET slug = 'coffee-quality-institute' WHERE term = 'Coffee Quality Institute';
UPDATE glossary_terms SET slug = 'coffee-sock' WHERE term = 'Coffee Sock';
UPDATE glossary_terms SET slug = 'coffee-culture' WHERE term = 'Coffee culture';
UPDATE glossary_terms SET slug = 'coffee-extraction' WHERE term = 'Coffee extraction';
UPDATE glossary_terms SET slug = 'coffee-filter' WHERE term = 'Coffee filter';
UPDATE glossary_terms SET slug = 'coffee-grinding' WHERE term = 'Coffee grinding';
UPDATE glossary_terms SET slug = 'fragrance-oil' WHERE term = 'Coffee oil';
UPDATE glossary_terms SET slug = 'coffee-percolator' WHERE term = 'Coffee percolator';
UPDATE glossary_terms SET slug = 'coffee-production' WHERE term = 'Coffee production';
UPDATE glossary_terms SET slug = 'coffee-tamping' WHERE term = 'Coffee tamping';
UPDATE glossary_terms SET slug = 'coffee-to-water-ratio' WHERE term = 'Coffee-to-Water Ratio';
UPDATE glossary_terms SET slug = 'coffeehouse' WHERE term = 'Coffeehouse';
UPDATE glossary_terms SET slug = 'coffeemaker' WHERE term = 'Coffeemaker';
UPDATE glossary_terms SET slug = 'cold-brew' WHERE term = 'Cold Brew Coffee';
UPDATE glossary_terms SET slug = 'cold-brew-coffee-maker' WHERE term = 'Cold Brew Coffee Maker';
UPDATE glossary_terms SET slug = 'complexity-in-coffee-a-symphony-of-flavors' WHERE term = 'Complexity in Coffee';
UPDATE glossary_terms SET slug = 'concentration' WHERE term = 'Concentration';
UPDATE glossary_terms SET slug = 'cortadito' WHERE term = 'Cortadito';
UPDATE glossary_terms SET slug = 'cortado' WHERE term = 'Cortado';
UPDATE glossary_terms SET slug = 'cowboy-coffee' WHERE term = 'Cowboy Coffee';
UPDATE glossary_terms SET slug = 'crema-quality' WHERE term = 'Crema Quality';
UPDATE glossary_terms SET slug = 'crust-in-coffee-cupping-an-essential-element' WHERE term = 'Crust in Coffee Cupping';
UPDATE glossary_terms SET slug = 'cuban-espresso' WHERE term = 'Cuban espresso';
UPDATE glossary_terms SET slug = 'cuisinart' WHERE term = 'Cuisinart';
UPDATE glossary_terms SET slug = 'cup' WHERE term = 'Cup';
UPDATE glossary_terms SET slug = 'dallah-coffee-pot' WHERE term = 'Dallah (coffee pot)';
UPDATE glossary_terms SET slug = 'dark-roast' WHERE term = 'Dark Roast';
UPDATE glossary_terms SET slug = 'decaffeination' WHERE term = 'Decaffeination';
UPDATE glossary_terms SET slug = 'decanter' WHERE term = 'Decanter';
UPDATE glossary_terms SET slug = 'carbon-dioxide' WHERE term = 'Degassing';
UPDATE glossary_terms SET slug = 'dementia' WHERE term = 'Dementia';
UPDATE glossary_terms SET slug = 'demitasse' WHERE term = 'Demitasse';
UPDATE glossary_terms SET slug = 'descaling' WHERE term = 'Descaling';
UPDATE glossary_terms SET slug = 'delonghi' WHERE term = 'De’Longhi';
UPDATE glossary_terms SET slug = 'diabetes-mellitus' WHERE term = 'Diabetes mellitus';
UPDATE glossary_terms SET slug = 'dialing-in' WHERE term = 'Dialing In';
UPDATE glossary_terms SET slug = 'dissolution-chemistry' WHERE term = 'Dissolution (chemistry)';
UPDATE glossary_terms SET slug = 'dolce-gusto' WHERE term = 'Dolce Gusto';
UPDATE glossary_terms SET slug = 'dorian-bodnariuc' WHERE term = 'Dorian Bodnariuc';
UPDATE glossary_terms SET slug = 'double' WHERE term = 'Double Espresso Shot';
UPDATE glossary_terms SET slug = 'drink' WHERE term = 'Drink';
UPDATE glossary_terms SET slug = 'drip-coffee' WHERE term = 'Drip Coffee';
UPDATE glossary_terms SET slug = 'drip-tray' WHERE term = 'Drip Tray';
UPDATE glossary_terms SET slug = 'dual-boiler' WHERE term = 'Dual Boiler';
UPDATE glossary_terms SET slug = 'dunkin-donuts' WHERE term = 'Dunkin’ Donuts';
UPDATE glossary_terms SET slug = 'e-61' WHERE term = 'E-61';
UPDATE glossary_terms SET slug = 'ese-pods' WHERE term = 'ESE pods';
UPDATE glossary_terms SET slug = 'earthy-coffee-a-flavor-profile' WHERE term = 'Earthy Coffee';
UPDATE glossary_terms SET slug = 'espressino' WHERE term = 'Espressino';
UPDATE glossary_terms SET slug = 'espresso' WHERE term = 'Espresso';
UPDATE glossary_terms SET slug = 'espresso-beans' WHERE term = 'Espresso Beans';
UPDATE glossary_terms SET slug = 'espresso-blend' WHERE term = 'Espresso Blend';
UPDATE glossary_terms SET slug = 'espresso-macchiato' WHERE term = 'Espresso Macchiato';
UPDATE glossary_terms SET slug = 'espresso-machine' WHERE term = 'Espresso Machine';
UPDATE glossary_terms SET slug = 'espresso-con-panna' WHERE term = 'Espresso con panna';
UPDATE glossary_terms SET slug = 'espro-p7' WHERE term = 'Espro P7';
UPDATE glossary_terms SET slug = 'ethiopia' WHERE term = 'Ethiopia';
UPDATE glossary_terms SET slug = 'extraction-time' WHERE term = 'Extraction Time';
UPDATE glossary_terms SET slug = 'extraction-yield' WHERE term = 'Extraction Yield';
UPDATE glossary_terms SET slug = 'ferment-flavor-in-coffee' WHERE term = 'Ferment Flavor in Coffee';
UPDATE glossary_terms SET slug = 'filtration' WHERE term = 'Filtration';
UPDATE glossary_terms SET slug = 'filtron' WHERE term = 'Filtron';
UPDATE glossary_terms SET slug = 'flat-coffee-what-does-it-mean' WHERE term = 'Flat Coffee';
UPDATE glossary_terms SET slug = 'flat-white' WHERE term = 'Flat white';
UPDATE glossary_terms SET slug = 'flavor' WHERE term = 'Flavor';
UPDATE glossary_terms SET slug = 'flavored-coffee' WHERE term = 'Flavored Coffee';
UPDATE glossary_terms SET slug = 'floral-notes-in-coffee-an-overview' WHERE term = 'Floral Notes in Coffee';
UPDATE glossary_terms SET slug = 'flow-rate' WHERE term = 'Flow Rate';
UPDATE glossary_terms SET slug = 'foam' WHERE term = 'Foam';
UPDATE glossary_terms SET slug = 'food' WHERE term = 'Food';
UPDATE glossary_terms SET slug = 'francisfrancis' WHERE term = 'Francis Francis!';
UPDATE glossary_terms SET slug = 'frappuccino' WHERE term = 'Frappuccino';
UPDATE glossary_terms SET slug = 'frappe' WHERE term = 'Frappé';
UPDATE glossary_terms SET slug = 'french-drip' WHERE term = 'French drip';
UPDATE glossary_terms SET slug = 'french-press' WHERE term = 'French press';
UPDATE glossary_terms SET slug = 'fruity-notes-in-coffee-an-overview' WHERE term = 'Fruity Notes in Coffee';
UPDATE glossary_terms SET slug = 'full-immersion' WHERE term = 'Full Immersion';
UPDATE glossary_terms SET slug = 'gaggia' WHERE term = 'Gaggia';
UPDATE glossary_terms SET slug = 'gaggia-classic-pro' WHERE term = 'Gaggia Classic Pro';
UPDATE glossary_terms SET slug = 'galao' WHERE term = 'Galão';
UPDATE glossary_terms SET slug = 'god-shot' WHERE term = 'God Shot';
UPDATE glossary_terms SET slug = 'grassy-notes-in-coffee-a-detailed-examination' WHERE term = 'Grassy Notes in Coffee';
UPDATE glossary_terms SET slug = 'grouphead' WHERE term = 'Grouphead';
UPDATE glossary_terms SET slug = 'hamilton-beach-brands' WHERE term = 'Hamilton Beach Brands';
UPDATE glossary_terms SET slug = 'handpresso' WHERE term = 'Handpresso';
UPDATE glossary_terms SET slug = 'hario' WHERE term = 'Hario';
UPDATE glossary_terms SET slug = 'hario-v60' WHERE term = 'Hario V60';
UPDATE glossary_terms SET slug = 'harsh-coffee-a-flavor-profile' WHERE term = 'Harsh Coffee';
UPDATE glossary_terms SET slug = 'heart' WHERE term = 'Heart';
UPDATE glossary_terms SET slug = 'heat-exchanger' WHERE term = 'Heat exchanger';
UPDATE glossary_terms SET slug = 'herbal-a-descriptor-in-coffee-tasting' WHERE term = 'Herbal';
UPDATE glossary_terms SET slug = 'hermetic-seal' WHERE term = 'Hermetic seal';
UPDATE glossary_terms SET slug = 'hidey-a-coffee-tasting-term' WHERE term = 'Hidey';
UPDATE glossary_terms SET slug = 'high-density-lipoprotein' WHERE term = 'High-density lipoprotein';
UPDATE glossary_terms SET slug = 'home-appliance' WHERE term = 'Home appliance';
UPDATE glossary_terms SET slug = 'hot-chocolate' WHERE term = 'Hot Chocolate';
UPDATE glossary_terms SET slug = 'hot-plate' WHERE term = 'Hot plate';
UPDATE glossary_terms SET slug = 'hypertension' WHERE term = 'Hypertension';
UPDATE glossary_terms SET slug = 'iced-latte' WHERE term = 'Iced Latte';
UPDATE glossary_terms SET slug = 'iced-coffee' WHERE term = 'Iced coffee';
UPDATE glossary_terms SET slug = 'iced-mocha' WHERE term = 'Iced mocha';
UPDATE glossary_terms SET slug = 'illy' WHERE term = 'Illy';
UPDATE glossary_terms SET slug = 'immersion-brewing' WHERE term = 'Immersion Brewing';
UPDATE glossary_terms SET slug = 'immersion-cold-brew' WHERE term = 'Immersion Cold Brew';
UPDATE glossary_terms SET slug = 'indian-filter-coffee' WHERE term = 'Indian Filter Coffee';
UPDATE glossary_terms SET slug = 'inka-beverage' WHERE term = 'Inka Beverage';
UPDATE glossary_terms SET slug = 'instant-taste-coffee-term' WHERE term = 'Instant Taste (Coffee Term)';
UPDATE glossary_terms SET slug = 'ipoh-white-coffee' WHERE term = 'Ipoh White Coffee';
UPDATE glossary_terms SET slug = 'irish-coffee' WHERE term = 'Irish coffee';
UPDATE glossary_terms SET slug = 'james-hoffmann' WHERE term = 'James Hoffmann';
UPDATE glossary_terms SET slug = 'joshua-spink' WHERE term = 'Joshua Spink';
UPDATE glossary_terms SET slug = 'jura-elektroapparate' WHERE term = 'Jura Elektroapparate';
UPDATE glossary_terms SET slug = 'kahweol' WHERE term = 'Kahweol';
UPDATE glossary_terms SET slug = 'kalita' WHERE term = 'Kalita';
UPDATE glossary_terms SET slug = 'karsk' WHERE term = 'Karsk';
UPDATE glossary_terms SET slug = 'kettle' WHERE term = 'Kettle';
UPDATE glossary_terms SET slug = 'keurig' WHERE term = 'Keurig';
UPDATE glossary_terms SET slug = 'kitchen' WHERE term = 'Kitchen';
UPDATE glossary_terms SET slug = 'kitchenaid' WHERE term = 'KitchenAid';
UPDATE glossary_terms SET slug = 'kopi-tubruk' WHERE term = 'Kopi Tubruk';
UPDATE glossary_terms SET slug = 'krups' WHERE term = 'Krups';
UPDATE glossary_terms SET slug = 'latte' WHERE term = 'Latte';
UPDATE glossary_terms SET slug = 'latte-art' WHERE term = 'Latte Art';
UPDATE glossary_terms SET slug = 'latte-macchiato' WHERE term = 'Latte macchiato';
UPDATE glossary_terms SET slug = 'lavazza' WHERE term = 'Lavazza';
UPDATE glossary_terms SET slug = 'lelit' WHERE term = 'Lelit';
UPDATE glossary_terms SET slug = 'light-roast' WHERE term = 'Light Roast';
UPDATE glossary_terms SET slug = 'long-black' WHERE term = 'Long black';
UPDATE glossary_terms SET slug = 'low-density-lipoprotein' WHERE term = 'Low-density lipoprotein';
UPDATE glossary_terms SET slug = 'lungo' WHERE term = 'Lungo';
UPDATE glossary_terms SET slug = 'macchiato' WHERE term = 'Macchiato';
UPDATE glossary_terms SET slug = 'malty-coffee-term' WHERE term = 'Malty (Coffee Term)';
UPDATE glossary_terms SET slug = 'manual-espresso-machine' WHERE term = 'Manual Espresso Machine';
UPDATE glossary_terms SET slug = 'mark-prince' WHERE term = 'Mark Prince';
UPDATE glossary_terms SET slug = 'marocchino' WHERE term = 'Marocchino';
UPDATE glossary_terms SET slug = 'mason-jar' WHERE term = 'Mason Jar';
UPDATE glossary_terms SET slug = 'mazagran' WHERE term = 'Mazagran';
UPDATE glossary_terms SET slug = 'medicinal-coffee-term' WHERE term = 'Medicinal (Coffee Term)';
UPDATE glossary_terms SET slug = 'medium-roast' WHERE term = 'Medium Roast';
UPDATE glossary_terms SET slug = 'medium-dark-roast' WHERE term = 'Medium-dark Roast';
UPDATE glossary_terms SET slug = 'melitta' WHERE term = 'Melitta';
UPDATE glossary_terms SET slug = 'mellow-coffee-flavor' WHERE term = 'Mellow Coffee Flavor';
UPDATE glossary_terms SET slug = 'melya' WHERE term = 'Melya';
UPDATE glossary_terms SET slug = 'microfoam' WHERE term = 'Microfoam';
UPDATE glossary_terms SET slug = 'milk-frother' WHERE term = 'Milk Frother';
UPDATE glossary_terms SET slug = 'mocha' WHERE term = 'Mocha';
UPDATE glossary_terms SET slug = 'mocha-java' WHERE term = 'Mocha Java';
UPDATE glossary_terms SET slug = 'moka-express' WHERE term = 'Moka Express';
UPDATE glossary_terms SET slug = 'moka-pot' WHERE term = 'Moka pot';
UPDATE glossary_terms SET slug = 'mr-coffee' WHERE term = 'Mr. Coffee';
UPDATE glossary_terms SET slug = 'mug' WHERE term = 'Mug';
UPDATE glossary_terms SET slug = 'muscle-contraction' WHERE term = 'Muscle contraction';
UPDATE glossary_terms SET slug = 'myocardial-infarction' WHERE term = 'Myocardial infarction';
UPDATE glossary_terms SET slug = 'national-coffee-association' WHERE term = 'National Coffee Association';
UPDATE glossary_terms SET slug = 'natural-rubber' WHERE term = 'Natural rubber';
UPDATE glossary_terms SET slug = 'nescafe' WHERE term = 'Nescafé';
UPDATE glossary_terms SET slug = 'nespresso' WHERE term = 'Nespresso';
UPDATE glossary_terms SET slug = 'nestle' WHERE term = 'Nestlé';
UPDATE glossary_terms SET slug = 'neutral-flavor-in-coffee' WHERE term = 'Neutral Flavor';
UPDATE glossary_terms SET slug = 'new-orleans' WHERE term = 'New Orleans';
UPDATE glossary_terms SET slug = 'nitro-cold-brew' WHERE term = 'Nitro Cold Brew';
UPDATE glossary_terms SET slug = 'normale' WHERE term = 'Normale';
UPDATE glossary_terms SET slug = 'nose-in-coffee-tasting' WHERE term = 'Nose in Coffee Tasting';
UPDATE glossary_terms SET slug = 'nutty-flavor-in-coffee-an-in-depth-look' WHERE term = 'Nutty Flavor in Coffee';
UPDATE glossary_terms SET slug = 'oxo-good-grips' WHERE term = 'OXO Good Grips';
UPDATE glossary_terms SET slug = 'oliang' WHERE term = 'Oliang';
UPDATE glossary_terms SET slug = 'oniony-in-coffee' WHERE term = 'Oniony in Coffee';
UPDATE glossary_terms SET slug = 'osteoporosis' WHERE term = 'Osteoporosis';
UPDATE glossary_terms SET slug = 'over-pressure-valve' WHERE term = 'Over Pressure Valve';
UPDATE glossary_terms SET slug = 'oxidation' WHERE term = 'Oxidation';
UPDATE glossary_terms SET slug = 'pid-controller' WHERE term = 'PID controller';
UPDATE glossary_terms SET slug = 'panarello-steam-wand' WHERE term = 'Panarello Steam Wand';
UPDATE glossary_terms SET slug = 'paper-filters' WHERE term = 'Paper Filters';
UPDATE glossary_terms SET slug = 'papery-flavor-in-coffee-an-unwanted-taste-profile' WHERE term = 'Papery Flavor in Coffee';
UPDATE glossary_terms SET slug = 'past-crop-the-impact-of-aging-on-coffee' WHERE term = 'Past Crop';
UPDATE glossary_terms SET slug = 'peaberry-coffee-2' WHERE term = 'Peaberry Coffee';
UPDATE glossary_terms SET slug = 'peasy-an-unpleasant-taste-in-coffee' WHERE term = 'Peasy';
UPDATE glossary_terms SET slug = 'caro-beverage' WHERE term = 'Pero';
UPDATE glossary_terms SET slug = 'philips' WHERE term = 'Philips';
UPDATE glossary_terms SET slug = 'plastic' WHERE term = 'Plastic';
UPDATE glossary_terms SET slug = 'plunger' WHERE term = 'Plunger';
UPDATE glossary_terms SET slug = 'pod-coffee-machine' WHERE term = 'Pod Coffee Machine';
UPDATE glossary_terms SET slug = 'polycarbonate' WHERE term = 'Polycarbonate';
UPDATE glossary_terms SET slug = 'porcelain' WHERE term = 'Porcelain';
UPDATE glossary_terms SET slug = 'postum' WHERE term = 'Postum';
UPDATE glossary_terms SET slug = 'pour-over-coffee' WHERE term = 'Pour over coffee';
UPDATE glossary_terms SET slug = 'pre-infusion' WHERE term = 'Pre-infusion';
UPDATE glossary_terms SET slug = 'pressure' WHERE term = 'Pressure';
UPDATE glossary_terms SET slug = 'pressure-profiling' WHERE term = 'Pressure Profiling';
UPDATE glossary_terms SET slug = 'pressure-gauge' WHERE term = 'Pressure gauge';
UPDATE glossary_terms SET slug = 'pressurized-basket' WHERE term = 'Pressurized Basket';
UPDATE glossary_terms SET slug = 'primary-tastes-in-coffee-a-sensory-exploration' WHERE term = 'Primary Tastes in Coffee';
UPDATE glossary_terms SET slug = 'puckpuck' WHERE term = 'Puckpuck';
UPDATE glossary_terms SET slug = 'quakery-in-coffee-a-flavor-profile' WHERE term = 'Quakery in Coffee';
UPDATE glossary_terms SET slug = 'rancid-flavor-in-coffee' WHERE term = 'Rancid Flavor in Coffee';
UPDATE glossary_terms SET slug = 'rancilio' WHERE term = 'Rancilio';
UPDATE glossary_terms SET slug = 'rancilio-silvia' WHERE term = 'Rancilio Silvia';
UPDATE glossary_terms SET slug = 'ready-to-drink-coffee' WHERE term = 'Ready-to-drink Coffee';
UPDATE glossary_terms SET slug = 'red-eye' WHERE term = 'Red eye';
UPDATE glossary_terms SET slug = 'review' WHERE term = 'Review';
UPDATE glossary_terms SET slug = 'ristretto' WHERE term = 'Ristretto';
UPDATE glossary_terms SET slug = 'robusta-coffee' WHERE term = 'Robusta coffee';
UPDATE glossary_terms SET slug = 'rubbery-flavor-in-coffee' WHERE term = 'Rubbery Flavor in Coffee';
UPDATE glossary_terms SET slug = 'scaa' WHERE term = 'SCAA';
UPDATE glossary_terms SET slug = 'saeco' WHERE term = 'Saeco';
UPDATE glossary_terms SET slug = 'scorched-coffee-an-exploration-of-over-roasting' WHERE term = 'Scorched Coffee';
UPDATE glossary_terms SET slug = 'screen-filter' WHERE term = 'Screen filter';
UPDATE glossary_terms SET slug = 'semi-automatic-espresso-machine' WHERE term = 'Semi Automatic Espresso Machine';
UPDATE glossary_terms SET slug = 'senseo' WHERE term = 'Senseo';
UPDATE glossary_terms SET slug = 'single' WHERE term = 'Single Espresso Shot';
UPDATE glossary_terms SET slug = 'single-origin' WHERE term = 'Single Origin';
UPDATE glossary_terms SET slug = 'single-origin-coffee' WHERE term = 'Single-origin coffee';
UPDATE glossary_terms SET slug = 'siphon-brewer' WHERE term = 'Siphon Brewer';
UPDATE glossary_terms SET slug = 'small-appliance' WHERE term = 'Small appliance';
UPDATE glossary_terms SET slug = 'smoothness-in-coffee-a-desirable-quality' WHERE term = 'Smoothness in Coffee';
UPDATE glossary_terms SET slug = 'solvent' WHERE term = 'Solvent';
UPDATE glossary_terms SET slug = 'sourness-in-coffee' WHERE term = 'Sourness in Coffee';
UPDATE glossary_terms SET slug = 'south-america' WHERE term = 'South America';
UPDATE glossary_terms SET slug = 'specialty-coffee' WHERE term = 'Specialty coffee';
UPDATE glossary_terms SET slug = 'spicy-notes-in-coffee-an-overview' WHERE term = 'Spicy Notes in Coffee';
UPDATE glossary_terms SET slug = 'stainless-steel' WHERE term = 'Stainless steel';
UPDATE glossary_terms SET slug = 'starbucks' WHERE term = 'Starbucks';
UPDATE glossary_terms SET slug = 'steam' WHERE term = 'Steam';
UPDATE glossary_terms SET slug = 'steam-wand' WHERE term = 'Steam Wand';
UPDATE glossary_terms SET slug = 'steamed-milk' WHERE term = 'Steamed Milk';
UPDATE glossary_terms SET slug = 'steampunk-coffeemaker' WHERE term = 'Steampunk coffeemaker';
UPDATE glossary_terms SET slug = 'steeping-time' WHERE term = 'Steeping Time';
UPDATE glossary_terms SET slug = 'stomach' WHERE term = 'Stomach';
UPDATE glossary_terms SET slug = 'stove' WHERE term = 'Stove';
UPDATE glossary_terms SET slug = 'super-automatic' WHERE term = 'Super Automatic Espresso Machine';
UPDATE glossary_terms SET slug = 'surface-area' WHERE term = 'Surface area';
UPDATE glossary_terms SET slug = 'taint' WHERE term = 'Taint';
UPDATE glossary_terms SET slug = 'takeya' WHERE term = 'Takeya';
UPDATE glossary_terms SET slug = 'tassimo' WHERE term = 'Tassimo';
UPDATE glossary_terms SET slug = 'taste' WHERE term = 'Taste';
UPDATE glossary_terms SET slug = 'technivorm' WHERE term = 'Technivorm';
UPDATE glossary_terms SET slug = 'temperature-surfing' WHERE term = 'Temperature Surfing';
UPDATE glossary_terms SET slug = 'temperature-control' WHERE term = 'Temperature control';
UPDATE glossary_terms SET slug = 'terroir' WHERE term = 'Terroir';
UPDATE glossary_terms SET slug = 'thermal-shock' WHERE term = 'Thermal shock';
UPDATE glossary_terms SET slug = 'thermoblock' WHERE term = 'Thermoblock';
UPDATE glossary_terms SET slug = 'thermocoil' WHERE term = 'Thermocoil';
UPDATE glossary_terms SET slug = 'thermostat' WHERE term = 'Thermostat';
UPDATE glossary_terms SET slug = 'thomas' WHERE term = 'Thomas';
UPDATE glossary_terms SET slug = 'timer' WHERE term = 'Timer';
UPDATE glossary_terms SET slug = 'tobacco-notes-in-coffee' WHERE term = 'Tobacco Notes in Coffee';
UPDATE glossary_terms SET slug = 'toddy' WHERE term = 'Toddy';
UPDATE glossary_terms SET slug = 'total-dissolved-solids' WHERE term = 'Total dissolved solids';
UPDATE glossary_terms SET slug = 'triple' WHERE term = 'Triple Espresso Shot';
UPDATE glossary_terms SET slug = 'turkish-coffee' WHERE term = 'Turkish coffee';
UPDATE glossary_terms SET slug = 'united-states' WHERE term = 'United States';
UPDATE glossary_terms SET slug = 'valve' WHERE term = 'Valve';
UPDATE glossary_terms SET slug = 'vibration' WHERE term = 'Vibration';
UPDATE glossary_terms SET slug = 'vienna' WHERE term = 'Vienna';
UPDATE glossary_terms SET slug = 'vietnamese-iced-coffee' WHERE term = 'Vietnamese iced coffee';
UPDATE glossary_terms SET slug = 'volatility-chemistry' WHERE term = 'Volatility (chemistry)';
UPDATE glossary_terms SET slug = 'water-tank' WHERE term = 'Water tank';
UPDATE glossary_terms SET slug = 'wiener-melange' WHERE term = 'Wiener Melange';
UPDATE glossary_terms SET slug = 'wigomat' WHERE term = 'Wigomat';
UPDATE glossary_terms SET slug = 'winey-coffee' WHERE term = 'Winey Coffee';
UPDATE glossary_terms SET slug = 'woody-coffee' WHERE term = 'Woody Coffee';
UPDATE glossary_terms SET slug = 'brew-group' WHERE term = 'brew group';
UPDATE glossary_terms SET slug = 'coffee' WHERE term = 'coffee';
UPDATE glossary_terms SET slug = 'coffee-beans' WHERE term = 'coffee beans';
UPDATE glossary_terms SET slug = 'grind-size' WHERE term = 'coffee grind size';
UPDATE glossary_terms SET slug = 'coffee-grinder' WHERE term = 'coffee grinder';
UPDATE glossary_terms SET slug = 'coffee-roasters' WHERE term = 'coffee roasters';
UPDATE glossary_terms SET slug = 'roasting' WHERE term = 'coffee roasting';
UPDATE glossary_terms SET slug = 'coffee-substitute' WHERE term = 'coffee substitute';
UPDATE glossary_terms SET slug = 'crema' WHERE term = 'crema';
UPDATE glossary_terms SET slug = 'dosing' WHERE term = 'dosing';
UPDATE glossary_terms SET slug = 'filter-basket' WHERE term = 'filter basket';
UPDATE glossary_terms SET slug = 'portafilter' WHERE term = 'portafilter';
UPDATE glossary_terms SET slug = 'single-serve-coffee-maker' WHERE term = 'single serve coffee maker';
UPDATE glossary_terms SET slug = 'tamper' WHERE term = 'tamper';
